[project]
name = "hello-python"
version = "0.1.0"
description = "Hello Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyright>=1.1.406",
    "ruff>=0.14.1",
]

[tool.ruff]
src = ["*.py"]
exclude = [
  "**/__pycache__",
  "**/.pytest_cache",
  "**/.venv",
  "**/venv",
  "**/htmlcov",
  "**/*env/*",
  "**/.git",
  "**/*.yaml",
  "**/*.yml",
]
line-length = 120
preview = true

[tool.ruff.lint.isort]
combine-as-imports = true
